### ISSUE TITLE
joep en auke hebben rare usernames

### ISSUE THREAD

**Issue by MatthijsvonPiekartz** [ArmouredSpacePony/SiegeOfZubrowka#1]
wat gaan we hieraan doen?

<issues test>

**Comment by shandrolis** [comment]
IS HET OMDAT IK ZWART BEN

**Comment by Randebiel** [comment]
JA

**Comment by Randebiel** [comment]
HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA
NIET LEUK!

**Comment by MatthijsvonPiekartz** [comment]
ja fuck dat ik ben de beheerder joep
